# Generated by Django 5.1 on 2024-08-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('crypto_id', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=4)),
                ('transaction_amount', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('user_age', models.IntegerField()),
                ('user_location', models.CharField(max_length=10)),
                ('crypto_price', models.FloatField()),
                ('market_trend', models.CharField(max_length=7)),
                ('user_balance', models.FloatField()),
            ],
        ),
    ]
